version: '3.8'
services:
  db:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - db:/data/db

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: some-db
    ports:
      - '5432:5432'
    volumes:
      - ./sql/setup.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db:
    driver:
      local